name = "All the Mods 9"
author = "ATMTeam"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "975ad6e02467f32b4d8e77137e22a5d39cb8cc6d15a37ad0c7603d3fd28383c1"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
